# Generated by Django 2.2.6 on 2020-04-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200422_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='account/avatars/%Y/%m/%d'),
        ),
    ]
