# Generated by Django 2.2.6 on 2020-04-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_articles', '0004_auto_20200421_1208'),
        ('account', '0011_favourites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='FavouriteArticles',
        ),
    ]
