# Generated by Django 2.2.6 on 2020-04-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_articles', '0004_auto_20200421_1208'),
        ('account', '0012_auto_20200427_0943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavouriteArticles',
            new_name='FavouriteArticle',
        ),
    ]
