# Generated by Django 2.2.6 on 2020-04-27 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200427_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_article', to='it_articles.Article'),
        ),
        migrations.AlterField(
            model_name='favouritearticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_article', to=settings.AUTH_USER_MODEL),
        ),
    ]
