# Generated by Django 3.0.5 on 2020-05-01 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it_articles', '0005_article_views'),
        ('account', '0015_auto_20200501_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_articles', to='it_articles.Article'),
        ),
        migrations.AlterField(
            model_name='favouritearticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
