# Generated by Django 3.0.5 on 2020-05-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20200501_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='sdhj', max_length=300),
            preserve_default=False,
        ),
    ]
