# Generated by Django 3.0.5 on 2020-05-28 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20200525_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivateUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activate_url', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
