# Generated by Django 3.0.5 on 2020-05-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='right_answer',
            new_name='is_right_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
