# Generated by Django 3.0.5 on 2020-05-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=20),
        ),
    ]
