# Generated by Django 2.2.6 on 2020-04-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
