# Generated by Django 3.0.5 on 2020-05-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_articles', '0006_auto_20200505_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='language',
        ),
    ]
