# Generated by Django 3.0.5 on 2020-05-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_articles', '0007_remove_article_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
